version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: pastemyst-mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - pastemyst-network

  api:
    image: codemyst/pastemyst-api:latest
    container_name: pastemyst-api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - ${API_PORT}:80
    environment:
      - ConnectionStrings:DefaultDb=mongodb://mongodb:27017
      - JwtSecret=${JWT_SECRET}
      - GitHub:ClientId=${GITHUB_CLIENT_ID}
      - GitHub:ClientSecret=${GITHUB_CLIENT_SECRET}
      - GitLab:ClientId=${GITLAB_CLIENT_ID}
      - GitLab:ClientSecret=${GITLAB_CLIENT_SECRET}
      - Host=${API_URL}
      - ClientUrl=${CLIENT_URL}
    depends_on:
      - mongodb
    networks:
      - pastemyst-network

  client:
    image: codemyst/pastemyst-client:latest
    container_name: pastemyst-client
    ports:
      - ${CLIENT_PORT}:3000
    environment:
      - PUBLIC_API_BASE=${API_URL}/api/v3
    networks:
      - pastemyst-network

networks:
  pastemyst-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
