version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: pastemyst-mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - pastemyst-network

  api:
    image: pastemyst-api-image
    container_name: pastemyst-api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - 5000:80
    environment:
      - ConnectionStrings:DefaultDb=mongodb://mongodb:27017
      - JwtSecret=${JWT_SECRET}
      - GitHub:ClientId=${GITHUB_CLIENT_ID}
      - GitHub:ClientSecret=${GITHUB_CLIENT_SECRET}
      - GitLab:ClientId=${GITLAB_CLIENT_ID}
      - GitLab:ClientSecret=${GITLAB_CLIENT_SECRET}
    depends_on:
      - mongodb
    networks:
      - pastemyst-network

  client:
    image: pastemyst-client-image
    container_name: pastemyst-client
    ports:
      - 3000:3000
    environment:
      - PUBLIC_API_BASE=http://host.docker.internal:5000/api/v3
    networks:
      - pastemyst-network

networks:
  pastemyst-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
