[api]
host = "http://localhost:5000"
port = 5000
https = false

[client]
host = "http://localhost:3000"

[database]
host = "localhost"
port = 5432
user = "pastemyst"
password = "epikepik"
database = "pastemyst"

[secrets]
jwt = "superepikstrongsecret"
session = "anotherstronksecret"

[github]
id = "id"
secret = "secret"

[gitlab]
id = "id"
secret = "secret"
