host: http://localhost:5000
port: 5000
clientHost: http://localhost:3000
https: false

dbHost: localhost
dbUser: pastemyst
dbPassword: epikepik
dbName: pastemyst
dbPort: 5432

sessionSecret: anotherstronksecret
jwtSecret: superepikstrongsecret

githubClientId: id
githubClientSecret: secret

gitlabClientId: id
gitlabClientSecret: secret
