name: Client

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: npm install
        run: |
          cd client
          npm install
      
      - name: lint
        run: |
          cd client
          npm run lint
      
      - name: check
        run: |
          cd client
          npm run check
          
      - name: build
        run: |
          cd client
          npm run build
